# Generated by Django 5.1.1 on 2025-01-25 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="slot_duration",
            field=models.CharField(
                choices=[("30", "30 Minutes"), ("60", "1 Hour")],
                default="30",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="max_appointments",
            field=models.PositiveIntegerField(
                default=4,
                help_text="Maximum number of appointments per two-hour block",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(8),
                ],
            ),
        ),
    ]
