# Generated by Django 5.1.1 on 2025-01-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_timeslot_slot_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="consultation_fee",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="department",
            field=models.CharField(default="", max_length=300),
        ),
    ]
