# Generated by Django 5.1.1 on 2025-01-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patientpro", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("type", "AB+"),
                    ("type", "AB-"),
                    ("type", "A+"),
                    ("type", "A-"),
                    ("type", "B+"),
                    ("type", "B-"),
                    ("type", "O+"),
                    ("type", "O-"),
                ],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="city",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="state",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="street",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="zipcode",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
