# Generated by Django 5.1.1 on 2025-01-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patientpro", "0002_patient_blood_group_patient_city_patient_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=6,
                null=True,
            ),
        ),
    ]
