# Generated by Django 5.1.1 on 2025-01-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patientpro", "0003_alter_patient_blood_group"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Appointment",
        ),
    ]
